name: scoring-credit
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - xgboost
  - mlflow
  - streamlit
  - fastapi
  - uvicorn
  - pip
  - pip:
      - shap
      - evidently
      - pytest